### PR TITLE
Provide status on waku protocol support

### PR DESCRIPTION
**Pull request by D4nte**

### CODE REVIEW

**Comment by D4nte** [comment]
@oskarth do you agree regarding support which is not planned?

**Comment by D4nte** [comment]
Related to https://github.com/vacp2p/rfc/issues/318

**Review by oskarth — APPROVED** [review]
Yes looks good! I guess for RPC there will be an equivalent JS API that could be speced out?

**Comment by D4nte** [comment]
> Yes looks good! I guess for RPC there will be an equivalent JS API that could be speced out?

Yes.

**Comment by D4nte** [comment]
bors merge

**Pull request merged**
