### PR TITLE
ci: add Jenkinsfile for building docs page

### PR DESCRIPTION
**Pull request by jakubgs**
CI setup that builds the `master` branch and pushes it to `gh-pages` branch in the repo which is published by GitHub pages.

Issue: https://github.com/status-im/js-waku/issues/355

### CODE REVIEW

**Comment by jakubgs** [comment]
There is a new `--cname` flag for `typedoc`, but it's not yet in any release, so I just added a `doc:cname` target:

* https://github.com/TypeStrong/typedoc/pull/1834

**Comment by D4nte** [comment]
@jakubgs
Thank you!

Just one blocking comment: the `.github/workflows/deploy-gh-pages.yml` file also deploys examples on GH pages.
Ultimately, I'd like to move these examples to *.demo.wakuconnect.dev but it's not urgent.

We can either keep the examples for now on GH pages and hence not delete the GitHub action workflow but just remove the doc deploy of it.
Or, we can migrate the examples at the same time.

As you can see from the workflow file, I have a number of examples: eth-pm, web-chat, eth-pm-wallet currently deployed in subfolders to the docs.
I'd be keen to deploy them to `eth-pm.demo.wakuconnect.dev`, `web-chat.wakuconnect.dev` and `eth-pm-wallet.demo.wakuconnect.dev`.

If you prefer to tackle that at the same times than the docs then please note that in the respective `package.json` files, we need to change the `homepage` field from `/js-waku` to `/`.

**Comment by jakubgs** [comment]
Do you think it makes sense to make a separate domain for every demo? Wouldn't it make more sense just to put them under https://js-waku.wakuconnect.dev/demo/ or https://js-waku.wakuconnect.dev/examples/ or something?

**Comment by D4nte** [comment]
> Do you think it makes sense to make a separate domain for every demo? Wouldn't it make more sense just to put them under [js-waku.wakuconnect.dev/demo](https://js-waku.wakuconnect.dev/demo/) or [js-waku.wakuconnect.dev/examples](https://js-waku.wakuconnect.dev/examples/) or something?

I am happy to go with subpath `/examples`. I am not sure what makes most sense. Happy either way.

**Review by D4nte — COMMENTED** [review]
LGTM

**Review by D4nte — APPROVED** [review]

**Pull request merged**
