### PR TITLE
Ignore patches and minor updates for examples/Add dependabot to angular-relay-chat

### PR DESCRIPTION
**Pull request by D4nte**
Too much noise.

### CODE REVIEW

**Review by jemboh — APPROVED** [review]
question... should I be added to the `reviewers` ?

apart from that... lgtm.

**Comment by D4nte** [comment]
> question... should I be added to the `reviewers` ?

i did ask a review:

image

Or are you referring to something else?

**Comment by D4nte** [comment]
bors merge

**Comment by D4nte** [comment]
Ok, just realized about the "reviewers" field of dependabot. Shall correct.

**Comment by D4nte** [comment]
bors merge

**Pull request merged**
